### ISSUE TITLE
Desktop notifications not working (Ubuntu)

### ISSUE THREAD

**Issue by Jes124** [RocketChat/Rocket.Chat.Electron#1053]
My system:

- Operating system: Ubuntu 18.04.1 LTS
- App version: 2.14.6

I do not receive any notifications while using the app Rochat.Chat desktop (downloaded through Ubuntu software). I did not change anything, and all the others apps do provide notifications (Thunderbird mail, Owncloud, etc.).

When I try the Test desktop notification button no notification appears. Here are my settings:

![image](https://user-images.githubusercontent.com/46489209/50835698-b1f1b100-1357-11e9-824f-071e7e8b1ca5.png)

![image](https://user-images.githubusercontent.com/46489209/50835723-c2a22700-1357-11e9-80e6-8331f0cef32a.png)

![image](https://user-images.githubusercontent.com/46489209/50835741-d188d980-1357-11e9-871d-7a0f3e09f53a.png)

Also, the notification settings of my desktop should be fine (again, didn't change anything there):

![image](https://user-images.githubusercontent.com/46489209/50835863-16147500-1358-11e9-94e1-3313d1136407.png)

EDIT: when I use the Rocket chat through my browser all notifications work.

**Comment by tassoevan** [comment]
I'm not sure, but maybe this should be classified as a snap issue too. @Jes124, do you installed it through Ubuntu Software, like @leandrohsilveira?

**Comment by oserban** [comment]
I think it's definitely a packaging/version issue:

1. (See screenshot bellow) The latest stable version has been updated to 2.14.6, while the candidate version remained 2.7.0. I reverted the snap to 2.7.0, which was the previous version published on the stable snap channel and it works well. Someone may have pushed 2.14.6 as a stable version instead of candidate. 
![image](https://user-images.githubusercontent.com/3008878/51050420-a953e180-15c8-11e9-89f6-8f4a86c74e2e.png)

2. If you install 2.14.6 version snap packaged, the notifications are not working as reported previously. I can also confirm that. They work well in version 2.7.0. If you want to revert to a working version (2.7.0) you can do a revert until you react version 2.7.0 (do this in a terminal):

```bash
sudo snap revert rocketchat-desktop
```

**Comment by oserban** [comment]
I can confirm that issue can be reproduced on 18.04 Ubuntu with rocketchat installed using the deb packaged (2.14.6) published on github release page. So this is not unique to the snap version.

**Comment by tassoevan** [comment]
Weird. I personally use Bionic (18.04) and I haven't noticed that, while the built snap looked like it was not following the Gnome look-and-feel. However, I changed the mechanism for notifications to keep some code cross-platform and ironically it failed for Windows and MacOS, which needed the change. I'll revert it.

**Comment by oserban** [comment]
The snap version has been updated to 2.14.7, but this made things worst unfortunately. The server settings were lost and I had to redo the setup. Plus there are a bunch of js errors raised for missing code/libraries:

 ```bash
Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/snap/rocketchat-desktop/9/resources/electron.asar/common/reset-search-paths.js:35:12)

```

**Comment by tassoevan** [comment]
@oserban Thanks for making me aware of it. No changes in the codebase explain these errors, therefore it must be a building/deploying issue.

**Comment by Jes124** [comment]
@tassoevan Yes, downloaded through Ubuntu software

**Comment by carl-di-ortus** [comment]
I had same problem in Centos7 with xfce4. Found a way to fix it: Menu -> Help -> Reset app data. It warns that configuration will be lost, something something will be lost, but it just actually fixed the problem and nothing else was touched.

I have seen multiple issues here with these notifications, so I suspect some spaghetti code around it exists (haven't checked and not really willing to). Posting here, so that you know it.

**Comment by dattn** [comment]
Same here. Rocketchat Snap version 2.14.7 on Ubuntu 18.10. A new install didn't change anything.
The "Reset app data" possible fix, did not work for me.

**Comment by oguhpereira** [comment]
@Jes124 
I received notification, but the button "Notification Test " don't work.

Are you testing with open.rocketchat or another server?

**Comment by philipooo** [comment]
We have the same issue but on windows. Clicking the **TEST DESKTOP NOTIFICATION** Button produces a Errormessage in the DevTools console.

> Uncaught (in promise) TypeError: g is not a function
    at 201f8e192f9ed2ed2b316010222f67a2251c89c8.js:221
    at 201f8e192f9ed2ed2b316010222f67a2251c89c8.js:1
    at <anonymous>

**Comment by tassoevan** [comment]
@philipooo It was an issue recently fixed in Rocket.Chat server. Updating the server to 0.74.3 should do the trick.

**Comment by gsbab** [comment]
Does someone know a workarround for this untill it is fixed? Because i don't want to miss any messages anymore.

**Comment by Jes124** [comment]
@oguhpereira We make use of an own private server via Rocketchat.

**Comment by gsbab** [comment]
Seems to be fixed in 2.15.0

**Comment by Jes124** [comment]
@gsbab Great, seems indeed fixed. Desktop notifications are working again and amount of unread messages are shown in the upright corner.

**Comment by phlegx** [comment]
Actually for me also the notifications are working. But the System tray icon is still not showing up (Ubuntu 16.04, deb)

**Comment by leandrohsilveira** [comment]
Updated to 2.15.0 client version and still not working.
But the company server is at 0.74.0 now.

**Comment by LittleNo** [comment]
Same here, clean install of Ubuntu 18.04, installed snap package 0.74.3

Client is on Windows 10 is version 2.15.2, same issue on mac os Client

Notification-Test works, but no real notifications at all appear

**Comment by archiebaer** [comment]
Not working. Help.

**Comment by archiebaer** [comment]
Test works.

**Comment by HeikoSchlittermann** [comment]
Again not working. Desktop 2.17.7, Server 3.0.2. Linux, Debian 10 with Gnome.

**Comment by bingosoft** [comment]
Confirming bug. Ubuntu 18.04. RC 2.17.7. Button "Test Desktop notifications" do nothing

**Comment by kovacsdavid** [comment]
Same here. Desktop notifications are not working. Ubuntu 19.04, RC 2.17.7. Test Desktop notifications button do nothing.

**Comment by pboesch** [comment]
Same on Debian 11

**Comment by HeikoSchlittermann** [comment]
pboesch <notifications@github.com> (Fr 13 Mär 2020 16:16:44 CET):
> Same on Debian 11

It may be related to "mute focused chats", I switched this off and now I
got notifications. But I didn't cross-check, if this was the root cause.

    Best regards from Dresden/Germany
    Viele Grüße aus Dresden
    Heiko Schlittermann
--
 SCHLITTERMANN.de ---------------------------- internet & unix support -
 Heiko Schlittermann, Dipl.-Ing. (TU) - {fon,fax}: +49.351.802998{1,3} -
 gnupg encrypted messages are welcome --------------- key ID: F69376CE -
 ! key id 7CBF764A and 972EAC9F are revoked since 2015-01 ------------ -

**Comment by pboesch** [comment]
> pboesch <notifications@github.com> (Fr 13 Mär 2020 16:16:44 CET):
> Same on Debian 11
> It may be related to "mute focused chats", I switched this off and now I got notifications. But I didn't cross-check, if this was the root cause. Best regards from Dresden/Germany Viele Grüße aus Dresden Heiko Schlittermann -- SCHLITTERMANN.de ---------------------------- internet & unix support - Heiko Schlittermann, Dipl.-Ing. (TU) - {fon,fax}: +49.351.802998{1,3} - gnupg encrypted messages are welcome --------------- key ID: F69376CE - ! key id 7CBF764A and 972EAC9F are revoked since 2015-01 ------------ -

Where do  you find this setting?

**Comment by HeikoSchlittermann** [comment]
pboesch <notifications@github.com> (Mo 16 Mär 2020 17:19:43 CET):
> > pboesch <notifications@github.com> (Fr 13 Mär 2020 16:16:44 CET):
> > Same on Debian 11
> > It may be related to "mute focused chats", I switched this off and now I got notifications. But I didn't cross-check, if this was the root cause. Best regards from Dresden/Germany Viele Grüße aus Dresden Heiko Schlittermann -- SCHLITTERMANN.de ---------------------------- internet & unix support - Heiko Schlittermann, Dipl.-Ing. (TU) - {fon,fax}: +49.351.802998{1,3} - gnupg encrypted messages are welcome --------------- key ID: F69376CE - ! key id 7CBF764A and 972EAC9F are revoked since 2015-01 ------------ -
>
> Where do  you find this setting?

    mon compte | preferences | alertes sonores | Mettre en sourdine les conversations ciblées

        [x] oi
        [ ] non     <-- I believe, this was the default


But using the "test notifications" button doesn't work either

--
Heiko

**Comment by vincentchalamon** [comment]
If that could help to debug, I got the following error message on the Developer Tools while trying to use the "test notifications" button:
> notifications.js:77
  Uncaught (in promise) TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (snap/rocketchat-desktop/157/resources/app.asar/node_modules/electron-fetch/lib/index.js:1220)
    at snap/rocketchat-desktop/157/resources/app.asar/node_modules/electron-fetch/lib/index.js:1293
    at new Promise (<anonymous>)
    at snap/rocketchat-desktop/157/resources/app.asar/node_modules/electron-fetch/lib/index.js:1290

**Comment by holyt** [comment]
**Ubuntu 18.04**
Installed via **snap**
Rocket chat client **2.17.10**
No notifications, test notification button do nothing.
Get the same error as [vincentchalamon](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1053#issuecomment-647352791)

**Comment by krystiangorecki** [comment]
Good observation about the reason can be found here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1509#issuecomment-629671004

**Comment by 7system7** [comment]
**Ubuntu 20.10**
Installed via **flatpak** (chat.rocket.RocketChat)
Rocket chat client **3.2.2**
No notifications, test notification button do nothing. :(

**Comment by Darkless012** [comment]
Notifications WERE working on RC client **3.1.1**, after upgrading to **3.2.2** it stopped working. Jeez...

**Comment by Yattien** [comment]
> Notifications WERE working on RC client **3.1.1**, after upgrading to **3.2.2** it stopped working. Jeez...

Upgrading to **3.2.3** fixed it here.

**Comment by vtx-team** [comment]
Hello, I am using Debian 11 Desktop and had the same symptom
latest/stable:    3.2.2 => No Desktop notification
latest/candidate: 3.3.0-snapshot => No Desktop notification
latest/edge:      3.7.0      => WORKING Desktop notification

Best Regards
