### ISSUE TITLE
Blank window on launch after update to 4.15.2 (revision 1136) — TypeError: dispatcher.getOwner is not a function

### ISSUE THREAD

**Issue by hafiz11339** [RocketChat/Rocket.Chat.Electron#3401]
### Describe the bug
  After the snap package auto-updated from revision 1071 to 1136 (Rocket.Chat Desktop 4.15.2),
  the app opens to a completely blank window (menu bar only, no content) on every launch.
 
  ### Steps to reproduce
  1. Have Rocket.Chat Desktop installed via snap on Linux, on the previous working build.
  2. Let it auto-update to 4.15.2 (revision 1136), or install 4.15.2 fresh.
  3. Launch the app.
  4. Window opens with only the OS/menu chrome — no UI ever renders.

  ### Expected behavior
  App renders normally, as it did on revision 1071.

  ### Environment
  - OS: Linux
  - Install method: snap, `latest/stable` channel
  - Broken version: 4.15.2 (snap revision 1136)
  - Last known-good version: revision 1071 (confirmed working, no errors in log)

  ### Relevant log output
  From `~/snap/rocketchat-desktop/1136/.config/Rocket.Chat/logs/main.log`,
  reproduced identically on every launch attempt:

  ```
  [error] [renderer:webview] [updates] TypeError: dispatcher.getOwner is not a function
      at getOwner (react/cjs/react.development.js:163:54)
      at process.env.NODE_ENV.exports.createElement (react.development.js:1052:9)
      at Provider (react-redux/dist/cjs/react-redux.development.cjs:955:32)
      at renderWithHooks (app/rootWindow-ilgT5oMP.js:330:106589)
      ...
  [error] [renderer:webview] [updates]
      at Provider (react-redux.development.cjs:923:11)
      at ErrorCatcher (app/rootWindow-ilgT5oMP.js:46137:1)
      at App (app/rootWindow-ilgT5oMP.js:46159:3)
  ```          
The crash happens inside the root `<Provider>` on first render and is caught by
  the app's own `ErrorCatcher`, so nothing ever paints. Revision 1071's logs from
  three days prior show no fatal errors under the same conditions — this appears
  to be a regression introduced in 4.15.x, possibly related to the Electron 40→42
  and Fuselage 0.58→0.78 upgrades shipped in 4.15.0 (#3372, #3373, #3349, #3353).

**Comment by oneiros-de** [comment]
If you are affected by the bug: use `sudo snap revert rocketchat-desktop` to revert to the previous working version.

**Comment by oneiros-de** [comment]
Seems to be fixed with 4.15.3
