### ISSUE TITLE
Rocket Chat app is invisible after install

### ISSUE THREAD

**Issue by johnypeterson** [RocketChat/Rocket.Chat.Electron#1804]
## My Setup

- Operating System: Windows 10 Pro
- App Version: 3.0.2
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
After installing the client on Windows the app creates the desktop icon, but when hovering the mouse over the icon it becomes invisible, And clicking the icon doesn't run the application

### Current Behavior
The icon of the application becomes invisible, And clicking the icon doesn't run the application

### Expected Behavior
The application should run when clicking the desktop icon

**Comment by IhorNykyha** [comment]
The same issues in version 3.0.3. @tassoevan I need your help. How to build package properly?
I perform:
yarn
yarn build 
yarn electron-builder --publish never --x64 (yarn release not included)
build exe-package, but after installation to the system, and start desktop chat, the desktop client is invisible. 
chat is present in system
![Screenshot_5](https://user-images.githubusercontent.com/46314384/96241973-9515f300-0fab-11eb-91cb-7fd757a0fcc0.png)
![Screenshot_4](https://user-images.githubusercontent.com/46314384/96241977-96dfb680-0fab-11eb-8cf5-c5ed162ec3b3.png)
![Screenshot_6](https://user-images.githubusercontent.com/46314384/96241981-9810e380-0fab-11eb-8f8d-6cb2d84b9413.png)

yarn start - works as expected

**Comment by Sx3** [comment]
Same issue with version 3.0.3 on windows 10
The installer is installing but the program does not work.
if we run the Rocket.Chat.exe from the **\dist\win-unpacked\** from CMD it is showing the following issue

```
Error: Cannot find module 'chokidar'
Require stack:
- E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron\dist\win-unpacked\resources\app.asar\app\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:919)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron\dist\win-unpacked\resources\app.asar\app\main.js:686:103 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\RocketChat_Dev_2020_2\\Rocket.Chat.Electron\\dist\\win-unpacked\\resources\\app.asar\\app\\main.js',
    undefined
  ]
}
```

**Comment by tassoevan** [comment]
@Sx3 The environment variable `NODE_ENV=production` is missing.

**Comment by IhorNykyha** [comment]
Hi. 
I set `NODE_ENV=production`, but nothing changed. In PowerShell, I have the same error as @Sx3

**Comment by IhorNykyha** [comment]
@tassoevan  Thanks a lot for your help

**Comment by Sx3** [comment]
Error #1 --------------------------------------------------------------------------------
Error: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
    at new GitHubPublisher (E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron-3.0.4\node_modules\electron-publish\src\gitHubPublisher.ts:47:15)
    at createPublisher (E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron-3.0.4\node_modules\app-builder-lib\src\publish\PublishManager.ts:273:14)
    at PublishManager.getOrCreatePublisher (E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron-3.0.4\node_modules\app-builder-lib\src\publish\PublishManager.ts:196:19)
    at PublishManager.scheduleUpload (E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron-3.0.4\node_modules\app-builder-lib\src\publish\PublishManager.ts:137:28)
    at PublishManager.artifactCreatedWithoutExplicitPublishConfig (E:\RocketChat_Dev_2020_2\Rocket.Chat.Electron-3.0.4\node_modules\app-builder-lib\src\publish\PublishManager.ts:180:14)

**Comment by Sx3** [comment]
> @tassoevan Thanks a lot for your help

is it worked for you?... if yes please share the fix :)

**Comment by IhorNykyha** [comment]
@Sx3  I set `$env:NODE_ENV="production"` before starting `yarn build`. Your new error about publishing to your repo, If you would like to publish a release to your repo, you must set env variable with your Github token `GH_TOKEN=yourtoken` or use the command `yarn electron-builder **--publish never** --x64 `. This error should not affect the build process.

**Comment by tassoevan** [comment]
You can also append the `publish` flag to the `release` script:
`yarn release --publish never`

**Comment by Sx3** [comment]
Got it working thanks !

**Comment by tassoevan** [comment]
@johnypeterson Any updates on newer versions?

**Comment by johnypeterson** [comment]
@tassoevan works on 3.0.4, thanks

**Comment by PedroFerreiraVOID** [comment]
> Error: Cannot find module 'chokidar'
@Sx3 Hi, I'm having the same issue, did you manage to resolve it? thanks

**Comment by starhound** [comment]
I as well am having the: Error: Cannot find module 'chokidar' error when running the unpacked exe from cmd.

**Comment by starhound** [comment]
> @Sx3 I set `$env:NODE_ENV="production"` before starting `yarn build`. Your new error about publishing to your repo, If you would like to publish a release to your repo, you must set env variable with your Github token `GH_TOKEN=yourtoken` or use the command `yarn electron-builder --publish never --x64 `. This error should not affect the build process.

After setting NODE_ENV my issue was resolved.

**Comment by timololipop** [comment]
> > @Sx3 I set `$env:NODE_ENV="production"` before starting `yarn build`. Your new error about publishing to your repo, If you would like to publish a release to your repo, you must set env variable with your Github token `GH_TOKEN=yourtoken` or use the command `yarn electron-builder --publish never --x64 `. This error should not affect the build process.
> 
> After setting NODE_ENV my issue was resolved.

Hey, how did you set it? I'm on Windows

**Comment by starhound** [comment]
Press Windows Key
Type in: Environment variables 

Select the "edit the system environment variables".

Select 4th button down: "Environment Variables..."

Add desired variables to the system one.

**Comment by starhound** [comment]
> > > @Sx3 I set `$env:NODE_ENV="production"` before starting `yarn build`. Your new error about publishing to your repo, If you would like to publish a release to your repo, you must set env variable with your Github token `GH_TOKEN=yourtoken` or use the command `yarn electron-builder --publish never --x64 `. This error should not affect the build process.
> > 
> > After setting NODE_ENV my issue was resolved.
> 
> Hey, how did you set it? I'm on Windows

See message above

**Comment by timololipop** [comment]
> > > > @Sx3 I set `$env:NODE_ENV="production"` before starting `yarn build`. Your new error about publishing to your repo, If you would like to publish a release to your repo, you must set env variable with your Github token `GH_TOKEN=yourtoken` or use the command `yarn electron-builder --publish never --x64 `. This error should not affect the build process.
> > > 
> > > 
> > > After setting NODE_ENV my issue was resolved.
> > 
> > 
> > Hey, how did you set it? I'm on Windows
> 
> See message above

Thank. you. so. much! I was struggling with that for so long now! Thank you!

**Comment by starhound** [comment]
> > > > > @Sx3 I set `$env:NODE_ENV="production"` before starting `yarn build`. Your new error about publishing to your repo, If you would like to publish a release to your repo, you must set env variable with your Github token `GH_TOKEN=yourtoken` or use the command `yarn electron-builder --publish never --x64 `. This error should not affect the build process.
> > > > 
> > > > 
> > > > After setting NODE_ENV my issue was resolved.
> > > 
> > > 
> > > Hey, how did you set it? I'm on Windows
> > 
> > See message above
> 
> Thank. you. so. much! I was struggling with that for so long now! Thank you!

Anytime! 

As far as I know the linux equivalent of that is just: 

export NODE_ENV="production"

Which is alot easier than navigating 3 menus.

**Comment by taihoa** [comment]
I tried the above methods but it doesn't work. Anyone who can fix it, please help me with step-by-step instructions. I need to build on Ubuntu.
Thanks everyone!
